apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv1
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv2
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv3
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
